# Generated by Django 4.0.2 on 2022-07-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='desc',
        ),
    ]
