# Generated by Django 4.0.2 on 2022-07-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_remove_company_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
    ]
