# Generated by Django 4.0.2 on 2022-07-15 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_remove_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('company', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.company')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.company')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='default.png', upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('desc', models.TextField(blank=True, max_length=100, null=True)),
                ('company', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.company')),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.TextField(blank=True, max_length=100, null=True)),
                ('reason2', models.TextField(blank=True, max_length=100, null=True)),
                ('reason3', models.TextField(blank=True, max_length=100, null=True)),
                ('icon1', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('icon2', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('icon3', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('title1', models.CharField(blank=True, max_length=25, null=True)),
                ('title2', models.CharField(blank=True, max_length=25, null=True)),
                ('title3', models.CharField(blank=True, max_length=25, null=True)),
                ('desc1', models.TextField(blank=True, max_length=100, null=True)),
                ('desc2', models.TextField(blank=True, max_length=100, null=True)),
                ('desc3', models.TextField(blank=True, max_length=100, null=True)),
                ('company', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Carroussel',
        ),
    ]
