# Generated by Django 4.0.2 on 2022-07-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_mainnew_new_service_whyus_delete_carroussel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyus',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='desc2',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='desc3',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='icon1',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='icon2',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='icon3',
        ),
    ]
