# Generated by Django 4.0.2 on 2022-07-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_remove_whyus_desc1_remove_whyus_desc2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AlterField(
            model_name='whyus',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.company'),
        ),
    ]
