# Generated by Django 4.0.2 on 2022-07-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_service_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='instagram',
        ),
    ]
