# Generated by Django 4.0.2 on 2022-07-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_remove_separator_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='logo',
            new_name='wallpapper',
        ),
        migrations.AlterField(
            model_name='separator',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
